apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "conductor-oss.fullname" . }}
  labels:
    {{- include "conductor-oss.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "conductor-oss.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        {{- include "conductor-oss.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - env:
          - name: spring.datasource.password
            value: {{ .Values.spring.datasource.password | quote }}
          - name: spring.datasource.username
            value: {{ .Values.spring.datasource.username | quote }}
          - name: spring.datasource.url
            value: {{ .Values.spring.datasource.url | quote }}
          - name: conductor.db.type
            value: {{ .Values.conductor.db.type | quote }}
          - name: conductor.queue.type
            value: {{ .Values.conductor.queue.type | quote }}
          - name: conductor.external-payload-storage.type
            value: {{ .Values.conductor.externalPayloadStorage.type | quote }}
          - name: conductor.indexing.enabled
            value: {{ .Values.conductor.indexing.enabled | quote }}
          - name: conductor.elasticsearch.url
            value: {{ .Values.conductor.indexing.elasticsearch.url | quote }}
          - name: conductor.elasticsearch.indexName
            value: {{ .Values.conductor.indexing.elasticsearch.indexName | quote }}
          - name: conductor.elasticsearch.version
            value: {{ .Values.conductor.indexing.elasticsearch.version | quote }}
          - name: conductor.elasticsearch.clusterHealthColor
            value: {{ .Values.conductor.indexing.elasticsearch.clusterHealthColor | quote }}
          - name: conductor.metrics-prometheus.enabled
            value: {{ .Values.conductor.metricsPrometheus.enabled | quote }}
          - name: loadSample
            value: {{ .Values.conductor.loadSample | quote }}
          - name: management.endpoints.web.exposure.include
            value: "prometheus"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          name: conductor-oss
          ports:
            - name: liveness-port
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.app.resources.cpuLimit | quote }}
              memory: {{ .Values.app.resources.memoryLimit | quote }}
            requests:
              cpu: {{ .Values.app.resources.cpuRequests | quote }}
              memory: {{ .Values.app.resources.memoryRequests | quote }}
          startupProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 30
            periodSeconds: 10
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30