replicaCount: 2

service:
  port: 5000

image:
  repository: ghcr.io/bacon-factory/conductor-oss
  tag: v3.21.3
  pullPolicy: Always
  livenessPort: 8080


app:
  resources:
    cpuLimit: "3"
    memoryLimit: "3Gi"
    cpuRequests: "2"
    memoryRequests: "2Gi"

conductor:
  db:
    type: postgres
  queue:
    type: postgres
  externalPayloadStorage:
    type: postgres
  indexing:
    enabled: "true"
    elasticsearch:
      url: http://es:9200
      indexName: conductor
      version: 7
      clusterHealthColor: yellow
  metricsPrometheus:
    enabled: "true"
  loadSample: "true"

spring:
  datasource:
    url: jdbc:postgresql://postgresdb:5432/postgres
    username: conductor
    password: conductor